### PR TITLE
fixed dill rewards chart and projections

### PR DESCRIPTION
**Pull request by bcstryker**

### CODE REVIEW

**Comment by bcstryker** [comment]
@mannyreimi88 check this out. looks way better than it used to and added some functionality. Let me know if there's anything you want added/removed/changed.

**Review by mannyreimi88 — CHANGES_REQUESTED** [review]
Please double-check these:

- [ ] APY on `DILL` SHOULD be higher for `PICKLE` than `ETH` component because rewards coming in the next distribution are higher on `PICKLE` than `ETH` terms, dollar-wise.
- [ ] cumulative charts are "up-only" charts, but it is not up-only on the monthly view. 
- [ ] there are lots of "invalid dates" for some reason.

**Comment by robstryker** [comment]
@mannyreimi88  Please include a screenshot in the future for the parts you feel are not correct.  It took me and stryker a while to understand the issue because we were only looking at the graph, not the section above it. Screenshots help.

**Comment by bcstryker** [comment]
@mannyreimi88 I fixed the issues you mentioned but I did not see any issues with invalid dates

Screen Shot 2022-08-19 at 3 36 25 PM
Screen Shot 2022-08-19 at 3 37 15 PM

**Comment by mannyreimi88** [comment]
> @mannyreimi88 Please include a screenshot in the future for the parts you feel are not correct. It took me and stryker a while to understand the issue because we were only looking at the graph, not the section above it. Screenshots help.

Screenshot 2022-08-22 at 9 11 05 AM

Screenshot 2022-08-22 at 9 11 17 AM

@bcstryker please use the debugger interface with my wallet `leekuanjew.eth` or `0x5c4D8CEE7dE74E31cE69E76276d862180545c307`

**Comment by rawbdor** [comment]
image

@mannyreimi88  It would be really really weird if wallet affected this at all bc this data is coming from pfcore json, and your wallet is not being used at all to query it.

**Comment by mannyreimi88** [comment]
@rawbdor sure but if this is released as-is, then, likely you'll hear from users the same complaint. My suggestion is to go to the alpha testers and see if anyone there gets the issue, or if you want do go ahead and merge and deal with the bug later when you have more data on what it could be.

**Comment by bcstryker** [comment]
addressed all subtasks addressed above. Discovered a continuing issue with "Invalid Date" appearing in the x-axis increment labels. Fixed issue and confirmed fix with two users who had experienced the same issue.

**Pull request merged**
