### PR TITLE
Fetch acceptable chains from pfcore lib (not json)

### PR DESCRIPTION
**Pull request by rawbdor**
Signed-off-by: rawbdor <rawblem@gmail.com>

### CODE REVIEW

**Comment by rawbdor** [comment]
Mind doing code review + vercel test for me?

**Comment by larrythecucumber321** [comment]
The changes here to `Connectors.ts` lgtm, thanks! 

Could you additionally apply pf-core to `Connection.ts`? Particularly the `switchChainParams` array. As-is, I'm still required to add new chains to this array, but this doesn't have to be the case if we're pf-coring things. The hexidecimal `chainId` can be obtained by `0x${pfcore.chainId.toString(16)}`.  Lastly, `setMulticallAddress` will have to be applied based on the configured multicall address in pf-core.

I suggest as a failsafe, if we're unable to fetch pf-core for whatever reason, we populate things with all the chains listed here https://chainid.network/chains.json, which @rawbdor and I have discussed (although this scenario still breaks multicall functionality... so we may perhaps still wish to configure multicall addresses manually).

**Review by bcstryker — COMMENTED** [review]
This will save us some headaches in the future. Everything looks good, unrelated but in testing I noticed that our site's behavior when wallet is connected but on an unsupported chain is kind of wonky compared to the changes we made to UIv2 last night. Might open an issue for this.

**Comment by robstryker** [comment]
> if we're unable to fetch pf-core for whatever reason

Just to note, if pf-core can't be loaded anymore, the whole site is likely dead as hell. We'd likely need a huge banner because the entire site is probably fucked.

**Pull request merged**
