### PR TITLE
Fixes #278 - show accurate pickle count from user data

### LINKED ISSUE #278: Update pickle count from user data on dashboard

### PR DESCRIPTION
**Pull request by rawbdor**
Signed-off-by: rawbdor <rawblem@gmail.com>

### CODE REVIEW

**Comment by rawbdor** [comment]
image

or

image


dependign on how many chains you have pickles on

**Comment by rawbdor** [comment]
image

If you have pickles on more than 1 chain

**Comment by janklimo** [comment]
@rawbdor do you have access to create branches directly in this repo so they get deployed?

**Review by bcstryker — APPROVED** [review]
Everything looks good, deployment tested and is functional, no errors.

**Pull request merged**
