### PR TITLE
Add 'Login with Unstoppable' as login option

### PR DESCRIPTION
**Pull request by denimcodes**
**Login with Unstoppable** is a simple login widget for applications that allows their users to create and authenticate logins as well as share contact information using their NFT domain.

## How It Works
Login with Unstoppable allows users to map their domains to an authorization server, which can authenticate and log users into an app.

1. Users can add a link to an authorization server to their domain.
2. When a user visits an app and logs in with their domain, the app reads the domain and directs the user to the
authorization server. If the user authenticates and grants access to the information the app requested, the
application receives an authorization containing an access token and an id token from the authorization server
with the user’s contact information (ie email address).
3. The app and user have now exchanged emails!

## Watch demo on Youtube

Link: https://www.youtube.com/watch?v=8mNs1gOzusE

## Setup
Create a .env file in the root folder with the following variables.

```
NEXT_PUBLIC_UAUTH_CLIENT_ID=
NEXT_PUBLIC_UAUTH_REDIRECT_URI=
```

## Libraries used

- [`@uauth/web3-react`](https://github.com/unstoppabledomains/uauth/tree/main/packages/web3-react) - Middleware used to help integrate @uauth/js into web3-react applications.

### CODE REVIEW

**Comment by bcstryker** [comment]
I personally appreciate you're hustle here but we're not looking to make a change, thanks anyway :)

**Comment by bcstryker** [comment]
@mannyreimi88 is this something we're interested in?

**Comment by rawbdor** [comment]
Hey sorry about the close:  we will evaluate this PR but do you think you can clean it up first? There's a lot of lines that aren't really changed and shouldn't be included in teh PR, like where imports are reordered or where the order of style classes has changed?

**Comment by bcstryker** [comment]
PR has been evaluated, but we are not looking to integrate additional connection options at this time. Thanks anyway and good hustle! Keep it up!

**Pull request closed without merging**
