### PR TITLE
Fixes #56 - use new jarApy api from pools endpoint

### LINKED ISSUE #56: Dill page innefficient, could avoid 20+ http requests?
https://github.com/pickle-finance/pickle-ui/blob/0c5bdcc4b2a670cd0881e52a9a025869eed9b1e1/containers/DILL/useProtocolIncome.ts#L17

In an attempt to get the weekly revenue projections, the dill page first accesses `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/pools` to get a list of jars + farms and their apy. 

This response includes the following:
```
identifier    "alcx-eth"
liquidity_locked    26180312.73
apy    175.25
```
The `apy` listed here matches the 3-day-farm apy from `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/jar/alcx-eth/performance`

The dill page then iterates through these assets and runs a separate request to the above performance url in order to fetch the 3-day JAR apy (which is NOT included in the original request). The number of requests done here is equal to the number of jar assets that were returned in the first request. The dill page then does math on this to get the revenues. 

These 20+ requests could be completely avoided if `prod/protocol/pools` returned both the 3-day farm apy AND the 3-day jar apy.

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

Using the build system to test. Yes, I'm not organized enough ;)

### CODE REVIEW

**Comment by robstryker** [comment]
couldnt help myself... coding in bed.   

seems to differ from current site by around $600 for revs, $300 for profit share or so. This also changes apy by about 1%.  I imagine these changes are expected (or at least within expected ranges). Compared every other number on the test page with the actual page (f5'd both at same time) and everything else seems to match.

**Comment by robstryker** [comment]
It's worth noting that, as far as I can tell,  "getAssetPerformanceData" only had 1 caller, which was this file. That function could theoretically be removed entirely, but I'm not confident enough in my search to remove it.

**Comment by robstryker** [comment]
Comparing weekly revenue projections. Right now:
old dill: Weekly protocol revenue: $265,189.38
new dill: Weekly protocol revenue: $288,052.59

Hard to tell which is more accurate without manually iterating to see where the discrepency comes from.

**Comment by robstryker** [comment]
Right now seeing $53,474.53 (new) vs 55,020.74 (old).  About a 3% variance.

**Comment by larrythecucumber321** [comment]
Woohoo! Thanks for taking this home @robstryker - lgtm and merged

**Pull request merged**
